---
version: '3'
services:
  api:
    image: blog-api-nest
    container_name: blog-api-nest
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE=blog-api-nest
      - AES_KEY=somerandomaeskey
      - JWT_SECRET=nonproductionsecret
      - SMTP_HOST=SMTP_HOST
      - SMTP_PORT=SMTP_PORT
      - SMTP_USERNAME=SMTP_USERNAME
      - SMTP_PASSWORD=SMTP_PASSWORD
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog-api-nest
    volumes:
      - postgres:/var/lib/postgresql/data/
